Lab2.class: Lab2.java
	javac Lab2.java

BadInstructionException.class: BadInstructionException.java
	javac BadInstructionException.java

BinaryCodes.class: BinaryCodes.java
	javac BinaryCodes.java

Instruction.class: Instruction.java
	javac Instruction.java

Label.class: Label.java
	javac Label.java

PassOne.class: PassOne.java
	javac PassOne.java	

PassTwo.class: PassTwo.java
	javac PassTwo.java

RegisterNotFoundException.class: RegisterNotFoundException.java
	javac RegisterNotFoundException.java

SyntaxException.class: SyntaxException.java
	javac SyntaxException.java

clean:
	rm *.class
